ctfd/data/CTFd/CTFd/forms/config.py
from wtforms import BooleanField, FileField, SelectField, StringField, TextAreaField
from wtforms.fields.html5 import IntegerField, URLField
from wtforms.widgets.html5 import NumberInput

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField
from CTFd.utils.csv import get_dumpable_tables


class ResetInstanceForm(BaseForm):
    accounts = BooleanField(
        "Accounts",
        description="Deletes all user and team accounts and their associated information",
    )
    submissions = BooleanField(
        "Submissions",
        description="Deletes all records that accounts gained points or took an action",
    )
    challenges = BooleanField(
        "Challenges", description="Deletes all challenges and associated data"
    )
    pages = BooleanField(
        "Pages", description="Deletes all pages and their associated files"
    )
    notifications = BooleanField(
        "Notifications", description="Deletes all notifications"
    )
    submit = SubmitField("Reset CTF")


class AccountSettingsForm(BaseForm):
    domain_whitelist = StringField(
        "Account Email Whitelist",
        description="Comma-seperated email domains which users can register under (e.g. ctfd.io, gmail.com, yahoo.com)",
    )
    team_creation = SelectField(
        "Team Creation",
        description="Control whether users can create their own teams (Teams mode only)",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )
    team_size = IntegerField(
        widget=NumberInput(min=0),
        description="Amount of users per team (Teams mode only)",
    )
    num_teams = IntegerField(
        "Total Number of Teams",
        widget=NumberInput(min=0),
        description="Max number of teams (Teams mode only)",
    )
    verify_emails = SelectField(
        "Verify Emails",
        description="Control whether users must confirm their email addresses before playing",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="false",
    )
    team_disbanding = SelectField(
        "Team Disbanding",
        description="Control whether team capatins are allowed to disband their own teams",
        choices=[
            ("inactive_only", "Enabled for Inactive Teams"),
            ("disabled", "Disabled"),
        ],
        default="inactive_only",
    )
    name_changes = SelectField(
        "Name Changes",
        description="Control whether users and teams can change their names",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )

    submit = SubmitField("Update")


class ExportCSVForm(BaseForm):
    table = SelectField("Database Table", choices=get_dumpable_tables())
    submit = SubmitField("Download CSV")


class ImportCSVForm(BaseForm):
    csv_type = SelectField(
        "CSV Type",
        choices=[("users", "Users"), ("teams", "Teams"), ("challenges", "Challenges")],
        description="Type of CSV data",
    )
    csv_file = FileField("CSV File", description="CSV file contents")


class LegalSettingsForm(BaseForm):
    tos_url = URLField(
        "Terms of Service URL",
        description="External URL to a Terms of Service document hosted elsewhere",
    )
    tos_text = TextAreaField(
        "Terms of Service", description="Text shown on the Terms of Service page",
    )
    privacy_url = URLField(
        "Privacy Policy URL",
        description="External URL to a Privacy Policy document hosted elsewhere",
    )
    privacy_text = TextAreaField(
        "Privacy Policy", description="Text shown on the Privacy Policy page",
    )
    submit = SubmitField("Update")

ctfd/data/CTFd/CTFd/forms/notifications.py
from wtforms import BooleanField, RadioField, StringField, TextAreaField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class NotificationForm(BaseForm):
    title = StringField("Title", description="Notification title")
    content = TextAreaField(
        "Content",
        description="Notification contents. Can consist of HTML and/or Markdown.",
    )
    type = RadioField(
        "Notification Type",
        choices=[("toast", "Toast"), ("alert", "Alert"), ("background", "Background")],
        default="toast",
        description="What type of notification users receive",
        validators=[InputRequired()],
    )
    sound = BooleanField(
        "Play Sound",
        default=True,
        description="Play sound for users when they receive the notification",
    )
    submit = SubmitField("Submit")

ctfd/data/CTFd/CTFd/forms/submissions.py
from wtforms import SelectField, StringField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class SubmissionSearchForm(BaseForm):
    field = SelectField(
        "Search Field",
        choices=[
            ("provided", "Provided"),
            ("id", "ID"),
            ("account_id", "Account ID"),
            ("challenge_id", "Challenge ID"),
            ("challenge_name", "Challenge Name"),
        ],
        default="provided",
        validators=[InputRequired()],
    )
    q = StringField("Parameter", validators=[InputRequired()])
    submit = SubmitField("Search")

ctfd/data/CTFd/forms/notifications.py
from wtforms import BooleanField, RadioField, StringField, TextAreaField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class NotificationForm(BaseForm):
    title = StringField("Title", description="Notification title")
    content = TextAreaField(
        "Content",
        description="Notification contents. Can consist of HTML and/or Markdown.",
    )
    type = RadioField(
        "Notification Type",
        choices=[("toast", "Toast"), ("alert", "Alert"), ("background", "Background")],
        default="toast",
        description="What type of notification users receive",
        validators=[InputRequired()],
    )
    sound = BooleanField(
        "Play Sound",
        default=True,
        description="Play sound for users when they receive the notification",
    )
    submit = SubmitField("Submit")

ctfd/data/CTFd/CTFd/api/v1/statistics/__init__.py
from flask_restx import Namespace

statistics_namespace = Namespace(
    "statistics", description="Endpoint to retrieve Statistics"
)

# isort:imports-firstparty
from CTFd.api.v1.statistics import challenges  # noqa: F401
from CTFd.api.v1.statistics import scores  # noqa: F401
from CTFd.api.v1.statistics import submissions  # noqa: F401
from CTFd.api.v1.statistics import teams  # noqa: F401
from CTFd.api.v1.statistics import users  # noqa: F401

ctfd/data/CTFd/CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

ctfd/data/CTFd/admin/__init__.py
import csv
import datetime
import os
from io import StringIO

from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

admin = Blueprint("admin", __name__)

# isort:imports-firstparty
from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import notifications  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401
from CTFd.cache import cache, clear_config, clear_pages, clear_standings
from CTFd.models import (
    Awards,
    Challenges,
    Configs,
    Notifications,
    Pages,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_config, set_config
from CTFd.utils.csv import dump_csv, load_challenges_csv, load_teams_csv, load_users_csv
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.exports import import_ctf as import_ctf_util
from CTFd.utils.helpers import get_errors
from CTFd.utils.security.auth import logout_user
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import is_admin


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d_%T")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/import/csv", methods=["POST"])
@admins_only
def import_csv():
    csv_type = request.form["csv_type"]
    # Try really hard to load data in properly no matter what nonsense Excel gave you
    raw = request.files["csv_file"].stream.read()
    try:
        csvdata = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            csvdata = raw.decode("cp1252")
        except UnicodeDecodeError:
            csvdata = raw.decode("latin-1")
    csvfile = StringIO(csvdata)

    loaders = {
        "challenges": load_challenges_csv,
        "users": load_users_csv,
        "teams": load_teams_csv,
    }

    loader = loaders[csv_type]
    reader = csv.DictReader(csvfile)
    loader(reader)
    return redirect(url_for("admin.config"))


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    output = dump_csv(name=table)

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    configs = Configs.query.all()
    configs = {c.key: get_config(c.key) for c in configs}

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template("admin/config.html", themes=themes, **configs)


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        require_setup = False
        logout = False
        next_url = url_for("admin.statistics")

        data = request.form

        if data.get("pages"):
            _pages = Pages.query.all()
            for p in _pages:
                for f in p.files:
                    delete_file(file_id=f.id)

            Pages.query.delete()

        if data.get("notifications"):
            Notifications.query.delete()

        if data.get("challenges"):
            _challenges = Challenges.query.all()
            for c in _challenges:
                for f in c.files:
                    delete_file(file_id=f.id)
            Challenges.query.delete()

        if data.get("accounts"):
            Users.query.delete()
            Teams.query.delete()
            require_setup = True
            logout = True

        if data.get("submissions"):
            Solves.query.delete()
            Submissions.query.delete()
            Awards.query.delete()
            Unlocks.query.delete()
            Tracking.query.delete()

        if require_setup:
            set_config("setup", False)
            cache.clear()
            logout_user()
            next_url = url_for("views.setup")

        db.session.commit()

        clear_pages()
        clear_standings()
        clear_config()

        if logout is True:
            cache.clear()
            logout_user()

        db.session.close()
        return redirect(next_url)

    return render_template("admin/reset.html")

ctfd/data/CTFd/api/v1/statistics/__init__.py
from flask_restx import Namespace

statistics_namespace = Namespace(
    "statistics", description="Endpoint to retrieve Statistics"
)

# isort:imports-firstparty
from CTFd.api.v1.statistics import challenges  # noqa: F401
from CTFd.api.v1.statistics import scores  # noqa: F401
from CTFd.api.v1.statistics import submissions  # noqa: F401
from CTFd.api.v1.statistics import teams  # noqa: F401
from CTFd.api.v1.statistics import users  # noqa: F401

ctfd/data/CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

ctfd/data/CTFd/themes/admin/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<title>Admin Panel</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ url_for('views.themes', theme='core', path='img/favicon.ico') }}" type="image/x-icon">
	<link rel="icon" href="{{ url_for('views.themes', theme='core', path='img/favicon.ico') }}" type="image/x-icon">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='core', path='css/fonts.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='core', path='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='admin', path='css/admin.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', theme='admin', path='css/codemirror.css') }}">
	<script type="text/javascript">
		var init = {
			'urlRoot': "{{ request.script_root }}",
			'csrfNonce': "{{ Session.nonce }}",
			'userMode': "{{ get_config('user_mode') }}",
			'userId': {{ id if (id is defined) else 0 }},
			'start': {{ get_config("start") | tojson }},
			'end': {{ get_config("end") | tojson }},
		}
	</script>
	{% block stylesheets %} {% endblock %}
	{% for stylesheet in get_registered_admin_stylesheets() %}
		{% if stylesheet.startswith('http') %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% elif request.script_root %}
			<link rel="stylesheet" type="text/css" href="{{ request.script_root }}/{{ stylesheet }}">
		{% else %}
			<link rel="stylesheet" type="text/css" href="{{ stylesheet }}">
		{% endif %}
	{% endfor %}
</head>

<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<div class="container">
			<a href="{{ url_for('views.static_html', route='/') }}" class="navbar-brand">CTFd</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#base-navbars"
					aria-controls="base-navbars" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="base-navbars">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.statistics') }}">Statistics</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.notifications') }}">Notifications</a>
					</li>
					<li class="nav-item dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Pages</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{{ url_for('admin.pages_listing') }}">All Pages</a>
							<a class="dropdown-item" href="{{ url_for('admin.pages_new') }}">New Page</a>
						</div>
					</li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.users_listing') }}">Users</a></li>
					{% if get_config('user_mode') == 'teams' %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.teams_listing') }}">Teams</a></li>
					{% endif %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.scoreboard_listing') }}">Scoreboard</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.challenges_listing') }}">Challenges</a></li>
					<li class="nav-item dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
						   aria-haspopup="true" aria-expanded="true">Submissions</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing') }}">All Submissions</a>
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing', submission_type='correct') }}">Correct Submissions</a>
							<a class="dropdown-item" href="{{ url_for('admin.submissions_listing', submission_type='incorrect') }}">Incorrect Submissions</a>
						</div>
					</li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('admin.config') }}">Config</a></li>

					{% set plugin_menu = get_admin_plugin_menu_bar() %}
					{% set plugins = get_configurable_plugins() %}
					{% if plugin_menu or plugins %}
						<li class="nav-item">
							<a class="nav-link d-none d-md-block d-lg-block">|</a>
						</li>

						{% for menu in plugin_menu %}
							{% if request.script_root %}
								{% set route = '/' + request.script_root + '/' + menu.route %}
							{% else %}
								{% set route = menu.route %}
							{% endif %}
							<li class="nav-item"><a class="nav-link" href="{{ route }}">{{ menu.title }}</a></li>
						{% endfor %}

						{% if plugins %}
						<li class="nav-item dropdown">
							<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Plugins <span class="caret"></span></a>
							<ul class="dropdown-menu">
									{% for plugin in plugins %}
											<a class="dropdown-item" href="{{ request.script_root }}{{ plugin.route }}">{{ plugin.name }}</a>
									{% endfor %}
							</ul>
						</li>
						{% endif %}
					{% endif %}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
						<a class="nav-link" href="https://docs.ctfd.io/" target="_blank">
							<i class="far fa-question-circle"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<main role="main">
		{% if get_config('version_latest') %}
		<div class="container-fluid bg-warning text-center py-3">
			<div class="row">
				<div class="col-md-12">
					<a class="btn btn-warning" href="{{ get_config('version_latest') }}">
						A new CTFd version is available!
					</a>
				</div>
			</div>
		</div>
		{% endif %}
		{% block content %}
		{% endblock %}
	</main>

	<footer class="footer pt-2">
		<div class="container text-center">
			<a href="https://ctfd.io" class="text-secondary">
				<small class="text-muted">
					Powered by CTFd
				</small>
			</a>
			<span>
				<small class="text-muted"><br> Version {{ get_config('ctf_version') }}</small>
			</span>
		</div>
	</footer>

	<script defer src="{{ url_for('views.themes', theme='admin', path='js/vendor.bundle.js') }}"></script>
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/core.js') }}"></script>
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/helpers.js') }}"></script>
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/components.js') }}"></script>

	{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/main.js') }}"></script>
	{% endblock %}

	{% block scripts %} {% endblock %}

	{% for script in get_registered_admin_scripts() %}
		{% if script.startswith('http') %}
			<script defer src="{{ script }}"></script>
		{% elif request.script_root %}
			<script defer src="{{ request.script_root }}/{{ script }}"></script>
		{% else %}
			<script defer src="{{ script }}"></script>
		{% endif %}
	{% endfor %}
</body>

</html>

ctfd/data/CTFd/themes/admin/templates/config.html
{% extends "admin/base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', theme='admin', path='css/codemirror.css') }}">
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Configuration</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<ul class="nav nav-pills flex-column">
				<li class="nav-item">
					<a class="nav-link rounded-0 active" href="#appearance" role="tab" data-toggle="tab">Appearance</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#theme" role="tab" data-toggle="tab">Theme</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#accounts" role="tab" data-toggle="tab">Accounts</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#fields" role="tab" data-toggle="tab">Custom Fields</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#mlc" role="tab" data-toggle="tab">MajorLeagueCyber</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#settings" role="tab" data-toggle="tab">Settings</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#security" role="tab" data-toggle="tab">Security</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#email" role="tab" data-toggle="tab">Email</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#ctftime" role="tab" data-toggle="tab">Time</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#legal" role="tab" data-toggle="tab">Legal</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#backup" role="tab" data-toggle="tab">Backup</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="#usermode" role="tab" data-toggle="tab">User Mode</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0" href="{{ url_for('admin.reset') }}" role="tab">Reset</a>
				</li>
			</ul>
		</div>
		<div class="col-md-9">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
					<span class="sr-only">Error:</span>
					{{ error }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
			{% endfor %}

			<div class="tab-content">
				{% include "admin/configs/appearance.html" %}

				{% include "admin/configs/theme.html" %}

				{% include "admin/configs/accounts.html" %}

				{% include "admin/configs/fields.html" %}

				{% include "admin/configs/mlc.html" %}

				{% include "admin/configs/settings.html" %}

				{% include "admin/configs/security.html" %}

				{% include "admin/configs/email.html" %}

				{% include "admin/configs/time.html" %}

				{% include "admin/configs/legal.html" %}

				{% include "admin/configs/backup.html" %}

				{% include "admin/configs/usermode.html" %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', theme='admin', path='js/pages/configs.js') }}"></script>
{% endblock %}